version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - backend_bundle:/usr/local/bundle
    environment:
      - DATABASE_URL=sqlite3:db/development.sqlite3
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    command: npm run dev

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./backend/db:/db
    environment:
      - SQLITE3_DB=/db/development.sqlite3

volumes:
  backend_bundle:
  frontend_node_modules: